-- This is a sample
-- The insert scripts are generated by `gen_file_download_summary`

INSERT INTO s4_classrep.equiclass_kiskki BY NAME
SELECT
    t."EQUI" AS equipment_id,
    try_cast(t1."ATFLV" AS INTEGER) AS kisk_base_height_mm,
    t2."ATWRT" AS kisk_cat_flap_available,
    try_cast(t3."ATFLV" AS INTEGER) AS kisk_depth_mm,
    try_cast(t4."ATFLV" AS INTEGER) AS kisk_height_mm,
    t5."ATWRT" AS kisk_material,
    try_cast(t6."ATFLV" AS INTEGER) AS kisk_width_mm,
    t7."ATWRT" AS location_on_site,
    try_cast(t8."ATFLV" AS INTEGER) AS manufacturers_asset_life_yr,
    t9."ATWRT" AS memo_line,
    t10."ATWRT" AS uniclass_code,
    t11."ATWRT" AS uniclass_desc,
FROM
    file_download_landing.classequi t
LEFT JOIN file_download_landing.valuaequi t1 ON t1."EQUI" = t."EQUI" AND t1."CHARID" = 'KISK_BASE_HEIGHT_MM'
LEFT JOIN file_download_landing.valuaequi t2 ON t2."EQUI" = t."EQUI" AND t2."CHARID" = 'KISK_CAT_FLAP_AVAILABLE'
LEFT JOIN file_download_landing.valuaequi t3 ON t3."EQUI" = t."EQUI" AND t3."CHARID" = 'KISK_DEPTH_MM'
LEFT JOIN file_download_landing.valuaequi t4 ON t4."EQUI" = t."EQUI" AND t4."CHARID" = 'KISK_HEIGHT_MM'
LEFT JOIN file_download_landing.valuaequi t5 ON t5."EQUI" = t."EQUI" AND t5."CHARID" = 'KISK_MATERIAL'
LEFT JOIN file_download_landing.valuaequi t6 ON t6."EQUI" = t."EQUI" AND t6."CHARID" = 'KISK_WIDTH_MM'
LEFT JOIN file_download_landing.valuaequi t7 ON t7."EQUI" = t."EQUI" AND t7."CHARID" = 'LOCATION_ON_SITE'
LEFT JOIN file_download_landing.valuaequi t8 ON t8."EQUI" = t."EQUI" AND t8."CHARID" = 'MANUFACTURERS_ASSET_LIFE_YR'
LEFT JOIN file_download_landing.valuaequi t9 ON t9."EQUI" = t."EQUI" AND t9."CHARID" = 'MEMO_LINE'
LEFT JOIN file_download_landing.valuaequi t10 ON t10."EQUI" = t."EQUI" AND t10."CHARID" = 'UNICLASS_CODE'
LEFT JOIN file_download_landing.valuaequi t11 ON t11."EQUI" = t."EQUI" AND t11."CHARID" = 'UNICLASS_DESC'
WHERE t."CLASS" = 'KISKKI';
