

CREATE OR REPLACE MACRO read_funcloc(file_name) AS TABLE
SELECT 
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'FUNCLOC',
        'ABCKZFLOC',
        'ABCKZI',
        'ANSWT',
        'ANSDT',
        'DEACT',
        'ANLN1_FL',
        'ANLNRI',
        'EINZLI',
        'BEGRUI',
        'BEGRU',
        'CGWLDT_FL',
        'VGWLDT_FL',
        'GSBE_FLOC',
        'GSBERI',
        'RBNR_FLOC',
        'BUKRSI',
        'BUKRSFLOC',
        'SUBMTI',
        'BAUMM',
        'SUBMTIFLO',
        'BAUJJ',
        'KOKRSI',
        'KOKR_FLOC',
        'KOST_FLOC',
        'KOSTLI',
        'HERLD',
        'WAERS',
        'LVORM',
        'TXTMI',
        'USTA_FLOC',
        'VTWEG',
        'SPART',
        'IEQUII',
        'EQUI_FLOC',
        'FLTYP',
        'BRGEW',
        'CGAERB_FL',
        'VGAERB_FL',
        'IEQUI',
        'INVNR',
        'LIZNR',
        'STOR_FLOC',
        'STORTI',
        'GEWRKFLOC',
        'INGR_FLOC',
        'RBNR_I',
        'INGRPI',
        'SWERKI',
        'SWERK_FL',
        'SERGE',
        'MAPAR',
        'HERST',
        'FLOC_REF',
        'CMGANR_FL',
        'VMGANR_FL',
        'TYPBZ',
        'OBJIDFLOC',
        'OBJTYFLOC',
        'EQART',
        'JOBJN_FL',
        'PPSIDI',
        'PLNT_FLOC',
        'BEBER_FL',
        'BEBERI',
        'WERGWFLOC',
        'IWERKI',
        'POSNR',
        'TRPNR1',
        'TRPNR',
        'MSGRP',
        'MSGRPI',
        'VKORG',
        'VKGRP',
        'VKBUR',
        'VKORGI',
        'AUFN_FLOC',
        'AUFNRI',
        'IFLOT_SRT',
        'EINZL',
        'GROES',
        'EQFNR',
        'DAUF_FLOC',
        'DAUFNI',
        'INBDT',
        'STATTEXT',
        'STSM_FLOC',
        'USTW_FLOC',
        'USWO_FLOC',
        'TPLKZ_FLC',
        'ANLA_FL',
        'TPLMA1',
        'TPLMA',
        'GEWEI',
        'STTXU',
        'DATBI_FLO',
        'PROI_FLOC',
        'PROIDI',
        'CGWLEN_FL',
        'VGWLEN_FL',
        'CWAGET_FL',
        'VWAGET_FL',
        'ARBPLFLOC',
        'LGWIDI',
        'MODELDESC',
        'MODELNAME',
        'MODELREF',
        'MODELRVER',
        'MODELVER',
        'ADRNR',
        'ADRNRI',
        'GEO_EXIST',
        'ALKEY',
        'MODELEXT'
    ],
    types = {
        'FUNCLOC': 'VARCHAR',
        'ABCKZFLOC': 'VARCHAR',
        'ANSWT': 'DECIMAL',
        'ANSDT': 'DATE',
        'CGWLDT_FL': 'DATE',
        'VGWLDT_FL': 'DATE',
        'KOST_FLOC': 'INTEGER',
        'FLTYP': 'INTEGER',
        'BRGEW': 'DECIMAL',
        'SWERK_FL': 'INTEGER',
        'PLNT_FLOC': 'INTEGER',
        'WERGWFLOC': 'INTEGER',
        'POSNR': 'INTEGER',
        'INBDT': 'DATE',
        'DATBI_FLO': 'DATE',
        'CGWLEN_FL': 'DATE',
        'VGWLEN_FL': 'DATE',
        'BAUMM': 'INTEGER',
        'BAUJJ': 'INTEGER',
        'KOKR_FLOC': 'INTEGER',
        'ADRNR': 'VARCHAR',
        'ALKEY': 'INTEGER',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
);


CREATE OR REPLACE MACRO read_classfloc(file_name) AS TABLE
SELECT 
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'FUNCLOC',
        'CLASS',
        'CLASSTYPE',
        'LKENZ_CLA',
        'CLINT',
        'CLSTATUS1',
    ],
    types = {
        'FUNCLOC': 'VARCHAR',
        'CLASSTYPE': 'VARCHAR',
        'CLINT': 'INTEGER',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
);

CREATE OR REPLACE MACRO read_valuafloc(file_name) AS TABLE
SELECT 
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'FUNCLOC',
        'ATAW1',
        'ATAWE',
        'ATAUT',
        'CHARID',
        'ATNAM',
        'ATWRT',
        'CLASSTYPE',
        'ATCOD',
        'ATVGLART',
        'TEXTBEZ',
        'ATZIS',
        'VALCNT',
        'ATIMB',
        'ATSRT',
        'ATFLV',
        'ATFLB',
    ],
    types = {
        'FUNCLOC': 'VARCHAR',
        'CHARID': 'VARCHAR',
        'ATWRT': 'VARCHAR',
        'CLASSTYPE': 'VARCHAR',
        'ATCOD': 'INTEGER',
        'TEXTBEZ': 'INTEGER',
        'ATZIS': 'INTEGER',
        'VALCNT': 'INTEGER',
        'ATSRT': 'INTEGER',
        'ATFLV': 'DECIMAL',
        'ATFLB': 'DECIMAL',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
);

CREATE OR REPLACE MACRO read_equi(file_name) AS TABLE
SELECT 
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'EQUI',
        'ABCK_EILO',
        'ABCKZI',
        'ANSWT',
        'ANSDT',
        'DEACT',
        'ANL1_EILO',
        'BEGRUI',
        'BEGRU',
        'CHAR2EQUI',
        'CGWLDT_EQ',
        'VGWLDT_EQ',
        'GSBE_EILO',
        'GSBERI',
        'RBNR_EEQZ',
        'ZZCLASS',
        'BUKRSI',
        'BUKR_EILO',
        'KMATN',
        'BAUMM_EQI',
        'SUBM_EEQZ',
        'BAUJJ',
        'KOKRSI',
        'KOKR_EILO',
        'KOST_EILO',
        'KOSTLI',
        'HERLD',
        'WAERS',
        'KUNDE_EQ',
        'KUNDE',
        'KUN1_EEQZ',
        'GEWRKI',
        'LVORM_EQI',
        'AULDT_EQI',
        'TXTMI',
        'USTA_EQUI',
        'VTWEG',
        'SPART',
        'KUN2_EEQZ',
        'EQTYP',
        'TPLNR_I',
        'TPLN_EILO',
        'BRGEW',
        'CGAERB_EQ',
        'VGAERB_EQ',
        'INVNR',
        'EQASP',
        'LSERNR',
        'LIZNR',
        'STOR_EILO',
        'STORTI',
        'EQ_LTEXT',
        'ARBP_EEQZ',
        'INGR_EEQZ',
        'RBNR_I',
        'INGRPI',
        'SWERKI',
        'SWER_EILO',
        'SERGE',
        'MAPA_EEQZ',
        'HERST',
        'CMGANR_EQ',
        'VMGANR_EQ',
        'MAT2EQUI',
        'MAT2EQUIC',
        'MAT_EQU',
        'SERNR',
        'TYPBZ',
        'OBJI_EILO',
        'OBJT_EQUI',
        'EQART_EQU',
        'KUN3_EEQZ',
        'PPSIDI',
        'PPLA_EEQZ',
        'WERK_EQUI',
        'BEBE_EILO',
        'BEBERI',
        'WERGW_EQI',
        'IWERKI',
        'HEQN_EEQZ',
        'KRFKZ',
        'MSGR_EILO',
        'MSGRPI',
        'VKORG',
        'VKGRP',
        'VKBUR',
        'VKORGI',
        'GERNR',
        'AUFN_EILO',
        'AUFNRI',
        'GROES_EQU',
        'EQFN_EILO',
        'EQFNRI',
        'DAUF_EILO',
        'DAUFNI',
        'INBDT',
        'STATTEXT',
        'STSM_EQUI',
        'USTW_EQUI',
        'USWO_EQUI',
        'LAGER_EQI',
        'ANL2_EILO',
        'HEQU_EEQZ',
        'TIDN_EEQZ',
        'GEWEI',
        'DATA_EEQZ',
        'DATB_EEQZ',
        'DATBI_EIL',
        'ELIEF_EQI',
        'PROI_EILO',
        'PROIDI',
        'CGWLEN_EQ',
        'VGWLEN_EQ',
        'CWAGET_EQ',
        'VWAGET_EQ',
        'ARBP_EILO',
        'AINEQ_IND',
        'MODELID',
        'AIN_EQUNR',
        'ADRNR',
        'ADRNRI',
        'COPY_FROM',
        'INSTIME',
        'INSDATE',
        'FRCRMV',
        'FRCFIT',
        'FUNCID',
        'GEO_EXIST',
        'IUID_TYPE',
        'UII_AGEN',
        'IS_MODEL',
        'PPEGUID',
        'UII_PLANT',
        'UII'
    ],
    types = {
        'EQUI': 'VARCHAR',
        'ABCK_EILO': 'VARCHAR',
        'ANSWT': 'DECIMAL',
        'ANSDT': 'DATE',
        'CGWLDT_EQ': 'DATE',
        'VGWLDT_EQ': 'DATE',
        'BUKR_EILO': 'INTEGER',
        'BAUMM_EQI': 'INTEGER',
        'BAUJJ': 'INTEGER',
        'KOKR_EILO': 'INTEGER',
        'AULDT_EQI': 'DATE',
        'BRGEW': 'DECIMAL',
        'SWER_EILO': 'INTEGER',
        'PPLA_EEQZ': 'INTEGER',
        'HEQN_EEQZ': 'INTEGER',
        'INBDT': 'DATE',
        'DATA_EEQZ': 'DATE',
        'DATB_EEQZ': 'DATE',
        'DATBI_EIL': 'DATE',
        'CGWLEN_EQ': 'DATE',
        'VGWLEN_EQ': 'DATE',
        'ADRNR': 'VARCHAR',
        'INSTIME': 'TIME',
        'INSDATE': 'DATE',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
);



CREATE OR REPLACE MACRO read_classequi(file_name) AS TABLE
SELECT
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'EQUI',
        'CLASS',
        'CLASSTYPE',
        'LKENZ_CLA',
        'CLINT',
        'ZZSTDCLAS',
        'CLSTATUS1',
    ],
    types = {
        'EQUI': 'VARCHAR',
        'CLASSTYPE': 'VARCHAR',
        'CLINT': 'INTEGER',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
);

CREATE OR REPLACE MACRO read_valuaequi(file_name) AS TABLE
SELECT
    *
FROM read_csv(
    file_name::VARCHAR,
    delim = '\t',
    comment = '*',
    header = false,
    dateformat='%d.%m.%Y',
    column_names = [
        'EQUI',
        'ATAW1',
        'ATAWE',
        'ATAUT',
        'CHARID',
        'ATNAM',
        'ATWRT',
        'CLASSTYPE',
        'ATCOD',
        'ATVGLART',
        'TEXTBEZ',
        'ATZIS',
        'VALCNT',
        'ATIMB',
        'ATSRT',
        'ATFLV',
        'ATFLB',
    ],
    types = {
        'EQUI': 'VARCHAR',
        'CHARID': 'VARCHAR',
        'ATWRT': 'VARCHAR',
        'CLASSTYPE': 'VARCHAR',
        'ATCOD': 'INTEGER',
        'TEXTBEZ': 'INTEGER',
        'ATZIS': 'INTEGER',
        'VALCNT': 'INTEGER',
        'ATSRT': 'INTEGER',
        'ATFLV': 'DECIMAL',
        'ATFLB': 'DECIMAL',
    },
    nullstr = ['00.00.0000', '00.00.00', '']
) t;

