-- This is a sample
-- The tables are generated by `gen_equi_translate`

CREATE OR REPLACE TABLE ai2_classrep.equiclass_electric_meter (
            ai2_reference VARCHAR NOT NULL,
            
            "HH_non HH site" VARCHAR,
            
            "MPAN number" DECIMAL(18, 3),
            
            "No of Broken Fibres Repaired" DECIMAL(18, 3),
            
            "No of Readings" VARCHAR,
            
            "Location On Site" VARCHAR,
            
            "Supply capacity" VARCHAR,
            
            PRIMARY KEY(ai2_reference)
        );
