-- This is a sample
-- The tables are generated by `gen_equi_translate`

CREATE OR REPLACE TABLE s4_classrep.equiclass_metrel (
            equipment_id VARCHAR NOT NULL,
            
            location_on_site VARCHAR,
            
            manufacturers_asset_life_yr INTEGER,
            
            memo_line VARCHAR,
            
            metr_hh_meter VARCHAR,
            
            metr_mpan_number BIGINT,
            
            metr_number_of_phase VARCHAR,
            
            metr_rated_voltage INTEGER,
            
            metr_rated_voltage_units VARCHAR,
            
            metr_sld_ref_no VARCHAR,
            
            uniclass_code VARCHAR,
            
            uniclass_desc VARCHAR,
            
            PRIMARY KEY(equipment_id)
        );
