-- This is a sample
-- The insert scripts are generated by `gen_equi_translate`

        INSERT INTO ai2_classrep.equiclass_electric_meter BY NAME
        SELECT
            t.ai2_reference AS ai2_reference,
            
            TRY_CAST(t1.attr_value AS VARCHAR) AS 'HH_non HH site',
            
            TRY_CAST(t2.attr_value AS VARCHAR) AS 'Location On Site',
            
            TRY_CAST(t3.attr_value AS DECIMAL(18, 3)) AS 'MPAN number',
            
            TRY_CAST(t4.attr_value AS DECIMAL(18, 3)) AS 'No of Broken Fibres Repaired',
            
            TRY_CAST(t5.attr_value AS VARCHAR) AS 'No of Readings',
            
            TRY_CAST(t6.attr_value AS VARCHAR) AS 'Supply capacity',
            
        FROM
            ai2_eav.vw_ai2_eav_worklist t
        
        LEFT JOIN ai2_eav.equipment_eav t1 ON t1.ai2_reference = t.ai2_reference AND t1.attr_name = 'HH&#x2F;non HH site'
        
        LEFT JOIN ai2_eav.equipment_eav t2 ON t2.ai2_reference = t.ai2_reference AND t2.attr_name = 'Location On Site'
        
        LEFT JOIN ai2_eav.equipment_eav t3 ON t3.ai2_reference = t.ai2_reference AND t3.attr_name = 'MPAN number'
        
        LEFT JOIN ai2_eav.equipment_eav t4 ON t4.ai2_reference = t.ai2_reference AND t4.attr_name = 'No of Broken Fibres Repaired'
        
        LEFT JOIN ai2_eav.equipment_eav t5 ON t5.ai2_reference = t.ai2_reference AND t5.attr_name = 'No of Readings'
        
        LEFT JOIN ai2_eav.equipment_eav t6 ON t6.ai2_reference = t.ai2_reference AND t6.attr_name = 'Supply capacity'
        
        WHERE t.equipment_type = 'EQUIPMENT: ELECTRIC METER';        

