
-- TODO - this needs to be generated by `gen_equi_translate` for all classes
INSERT INTO excel_uploader_equi_create.classification BY NAME
SELECT * FROM get_excel_loader_characteristics_for('METREL', s4_classrep.equiclass_metrel)